production:
  adapter: postgresql
  encoding: utf8
  database: udl_logger
  username: postgres
  password: 92033
  host: 41.242.1.69
  port: 5432
  pool: 15

development:
  adapter:  postgresql
  host:     localhost
  # encoding: unicode
  database: udl_development
  pool:     5
  username: postgres
  password: 92033

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: udl_test
  pool:     5
  username: postgres
  password: 92033